# 异常
::: tip
本文主要对Java的异常进行总结。@Frank Zhao
:::
## 本章目录
[[toc]]
## 异常概述
Java异常是Java提供的一种识别及响应错误的一致性机制。<br>
Java异常机制可以使程序中异常处理代码和正常业务代码分离，保证程序代码更加优雅，并提高程序健壮性。<br>
* 在有效使用异常的情况下，异常能清晰的回答what, where, why这3个问题：
   * 异常类型回答了“什么”被抛出
   * 异常堆栈跟踪回答了“在哪“抛出
   * 异常信息回答了“为什么“会抛出
## 异常的层次结构
<div>
    <img src="/images/java/java-basic-exception-1.png" width="70%" height="70%" />
</div>

### Throwable
Throwable是 Java 语言中所有错误或异常的超类。<br>
Throwable包含两个子类: Error（错误）和 Exception（异常），它们通常用于指示发生了异常情况。<br>
Throwable包含了其线程创建时线程执行堆栈的快照，它提供了printStackTrace()等接口用于获取堆栈跟踪数据等信息。<br>
### Exception
程序本身可以捕获并且可以处理的异常。<br>
Exception 这种异常又分为两类：运行时异常和编译时异常。<br>
* 运行时异常（RuntimeException）
   * RuntimeException是那些可能在 Java 虚拟机正常运行期间抛出的异常的超类。
   * 运行时异常Java编译器是不检查的，程序中可以选择捕获处理，也可以不处理。
      * 也就是说，当程序中可能出现这类异常，即使没有用try-catch语句捕获它，也没有用throws子句声明抛出它，也会编译通过。
   * 这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生。
* 非运行时异常 （编译异常）
   *  RuntimeException以外的异常
   *  从程序语法角度讲是必须进行处理的异常，如果不处理，程序就不能编译通过。
   *  一般情况下不自定义可检查的异常。
<br><br>
* 可查的异常（编译器要求必须处置的异常）（checked exceptions）
   * Exception类本身，以及Exception的子类中除了"运行时异常"之外的其它子类都属于被检查异常。
   * Java编译器会检查它。此类异常，要么通过throws进行声明抛出，要么通过try-catch进行捕获处理，否则不能通过编译。
   * 被检查异常通常都是可以恢复的。
* 不可查的异常（编译器不要求强制处置的异常）（unchecked exceptions）
   * 运行时异常（RuntimeException与其子类）
   * 错误（Error）
<br><br>
### Error
Error表示运行应用程序中出现了严重的错误。<br>
Error是程序中无法处理的错误，这些错误是不受检异常，非代码性错误。<br>
因此，当此类错误发生时，应用程序不应该去处理此类错误。<br>
编译器也不会检查Error<br>
按照Java惯例，我们是不应该实现任何新的Error子类的<br>
此类错误一般表示代码运行时 JVM 出现问题，此类错误发生时，JVM 将终止线程。
## 异常语法 
### try 
用于监听。<br>
将要被监听的代码（可能抛出异常的代码）放在try语句块之内，当try语句块内发生异常时，异常就被抛出。<br>
### catch 
用于捕获异常。<br>
catch用来捕获try语句块中发生的异常。<br>
### finally 
finally语句块总是会被执行。<br>
它主要用于回收在try块里打开的资源（如数据库连接、网络连接和磁盘文件）。<br>
只有finally块，执行完成之后，才会回来执行try或者catch块中的return或者throw语句<br>
如果finally中使用了return或者throw等终止方法的语句，则就不会跳回执行，直接停止。<br>
### throw 
用于抛出异常。
``` java
public static double method(int value) {
    if (value == 0) {
        // 抛出一个运行时异常
        throw new ArithmeticException("参数不能为0"); 
    }
    return 5.0 / value;
}
```
### throws
用在方法签名中，用于声明该方法可能抛出的异常。<br>
若方法中存在检查异常，如果不对其捕获，那必须在方法头中显式声明该异常，以便于告知方法调用者此方法有异常，需要进行处理。 <br>
在方法中声明一个异常，方法头中使用关键字throws，后面接上要声明的异常。<br>
若声明多个异常，则使用逗号分割。如下所示：
``` java
public static void method() throws IOException, FileNotFoundException {
    // something statements
}
```
::: danger
若是父类的方法没有声明异常，则子类继承方法后，也不能声明异常。
:::
::: warning
通常，应该捕获那些知道如何处理的异常，将不知道如何处理的异常继续传递下去。
:::
## 异常方法
### getCause() 
取得原始异常
``` java
Throwable th = e.getCause()
```
### addSuppressed()
将一个异常附加到另一个异常身上，从而避免异常屏蔽问题。
``` java
var2.addSuppressed(var11);
```
## 自定义异常
* 习惯上，定义一个异常类应包含两个构造函数，
   * 一个无参构造函数
   * 一个带有详细描述信息的构造函数（Throwable 的 toString 方法会打印这些详细信息，调试时很有用）
``` java
public class MyException extends Exception {
    // 异常信息
    private String message;
    // 无参构造函数
    public MyException(){ }
    // 构造函数
    public MyException(String msg){
        super(msg);        
        this.message = message;
    }
    // ...
}
```
## 常用的异常
* RuntimeException 
   * java.lang.ArrayIndexOutOfBoundsException 
      * 数组索引越界异常。当对数组的索引值为负数或大于等于数组大小时抛出。 
   * java.lang.ArithmeticException 
      * 算术条件异常。譬如：整数除零等。 
   * java.lang.NullPointerException 
      * 空指针异常。
      * 当应用试图在要求使用对象的地方使用了null时，抛出该异常。
      * 譬如：调用null对象的实例方法、访问null对象的属性、计算null对象的长度、使用throw语句抛出null等等 
   * java.lang.ClassNotFoundException 
      * 找不到类异常。
      * 当应用试图根据字符串形式的类名构造类，而在遍历CLASSPAH之后找不到对应名称的class文件时，抛出该异常。 
   * java.lang.NegativeArraySizeException 
      *  数组长度为负异常 
   * java.lang.ArrayStoreException 
      * 数组中包含不兼容的值抛出的异常 
   * java.lang.SecurityException 
      * 安全性异常 
   * java.lang.IllegalArgumentException 
      * 非法参数异常 
* IOException 
   * IOException
      * 操作输入流和输出流时可能出现的异常。 
   * EOFException   
      * 文件已结束异常 
   * FileNotFoundException   
      * 文件未找到异常 
* 其他 
   * ClassCastException    
      * 类型转换异常类 
   * ArrayStoreException  
      * 数组中包含不兼容的值抛出的异常 
   * SQLException   
      * 操作数据库异常类 
   * NoSuchFieldException   
      * 字段未找到异常 
   * NoSuchMethodException   
      * 方法未找到抛出的异常 
   * NumberFormatException    
      * 字符串转换为数字抛出的异常 
   * StringIndexOutOfBoundsException 
      * 字符串索引超出范围抛出的异常 
   * IllegalAccessException  
      * 不允许访问某类异常 
   * InstantiationException  
      * 当应用程序试图使用Class类中的newInstance()方法创建一个类的实例，而指定的类对象无法被实例化时，抛出该异常
## 异常实践
这里给出几个被很多团队使用的异常处理最佳实践。
* 异常只应该被用于不正常的条件，它们永远不应该被用于正常的控制流。
   * Java 类库中定义的可以通过预检查方式规避的RuntimeException异常不应该通过catch 的方式来处理，比如：NullPointerException，IndexOutOfBoundsException等等。 
* 在 finally 块中清理资源或者使用 try-with-resource 语句
* 对异常进行文档说明
   * 在 Javadoc 添加 @throws 声明，并且描述抛出异常的场景。
* 优先捕获最具体的异常，按照子类在前，父类在后的原则
* 不要捕获 Throwable 类
* 不要在finally块中使用return
* 自定义异常时不要抛弃原始的异常
   * Exception 类提供了特殊的构造函数方法，它接受一个 Throwable 作为参数。
   * 否则，你将会丢失堆栈跟踪和原始异常的消息，这将会使分析导致异常的异常事件变得困难。 
``` java
public void wrapException(String input) throws MyBusinessException {
    try {
        // do something
    } catch (NumberFormatException e) {
        throw new MyBusinessException("A message that describes the error.", e);
    }
}
```
## 异常分析
### 第一个程序
::: details 代码实例解析
``` java
import java.io.IOException;
public class Test {
    public static void main(String[] args) {
        try {
            System.out.println("Hello world");
        } catch(IOException e) {
            System.out.println("I've never seen println fail!");
        }
    }
}	
```
编译出错！<br>
错误信息：java: 在相应的 try 语句主体中不能抛出异常错误java.io.IOException<br>
这个程序不能编译，因为 println 方法没有声明会抛出任何被检查异常，而IOException 却正是一个被检查异常。<br>
语言规范中描述道：如果一个 catch 子句要捕获一个类型为 E 的被检查异常, 而其相对应的 try 子句不能抛出 E 的某种子类型的异常，那么这就是一个编译期错误。<br>
:::
### 第二个程序
::: details 代码实例解析
``` java
public class Test {
    public static void main(String[] args) {
        try {
            // If you have nothing nice to say, say nothing
        } catch(Exception e) {
            System.out.println("This can't happen");
        }
    }
}
```
看起来应该是不可以编译的，但是它却可以。<br>	
它之所以可以编译，是因为它唯一的 catch 子句检查了 Exception。	<br>
尽管在这一点上十分含混不清，但是捕获 Exception 或 Throwble 的 catch 子句是合法的，不管与其相对应的 try 子句的内容为何。	<br>
尽管这是一个合法的程序，但是 catch 子句的内容永远的不会被执行，这个程序什么都不会打印。<br>
:::
### 第三个程序
::: details 代码实例解析
``` java
public class Test {
    public static final long GUEST_USER_ID = -1;
    private static final long USER_ID;

    static {
        try {
            USER_ID = getUserIdFromEnvironment();
        } catch (IdUnavailableException e) {
            USER_ID = GUEST_USER_ID;
            System.out.println("Logging in as guest");
        }
    }

    private static long getUserIdFromEnvironment()
            throws IdUnavailableException {
        throw new IdUnavailableException();
    }

    public static void main(String[] args) {
        System.out.println("User ID: " + USER_ID);
    }
}

class IdUnavailableException extends Exception {
}
```
编译错误<br>
错误信息：java: 可能已分配变量USER_ID<br><br>
该程序看起来很直观。<br>										
对 getUserIdFromEnvironment 的调用将抛出一个异常, 从而使程序将 GUEST_USER_ID 赋值给 USER_ID, 并打印 Loggin in as guest。<br> 
然后 main 方法执行，使程序打印 User ID: -1。	<br>									
表象再次欺骗了我们，该程序并不能编译。如果你尝试着去编译它, 你将看到和一条错误信息。<br>										
* 问题出在哪里了?										
   * USER_ID 域是一个空 final，它是一个在声明中没有进行初始化操作的 final 域。									
   * 很明显，只有在对 USER_ID 赋值失败时，才会在 try 语句块中抛出异常，因此，在 catch 语句块中赋值是相当安全的。				   
   * 不管怎样执行静态初始化操作语句块，只会对 USER_ID 赋值一次，这正是空 final 所要求的。									
* 为什么编译器不知道这些呢? 										
   * 要确定一个程序是否可以不止一次地对一个空 final 进行赋值是一个很困难的问题。									
   * 事实上，这是不可能的。这等价于经典的停机问题，它通常被认为是不可能解决的。									
   * 为了能够编写出一个编译器，语言规范在这一点上采用了保守的方式。									
   * 在程序中，一个空 final 域只有在它是明确未赋过值的地方才可以被赋值。									
   * 规范长篇大，对此术语提供了一个准确的但保守的定义。									
   * 因为它是保守的，所以编译器必须拒绝某些可以证明是安全的程序。这个谜题就展示了这样的一个程序。								

<br>解决这类问题的最好方式就是将这个烦人的域从空 final 类型改变为普通的final 类型，用一个静态域的初始化操作替换掉静态的初始化语句块。<br>	
实现这一点的最佳方式是重构静态语句块中的代码为一个助手方法:	<br>									
``` java
public class Test {
    public static final long GUEST_USER_ID = -1;
    private static final long USER_ID = getUserIdOrGuest();
    private static long getUserIdOrGuest() {
        try {
            return getUserIdFromEnvironment();
        } catch (IdUnavailableException e) {
            System.out.println("Logging in as guest");
            return GUEST_USER_ID;
        }
    }

    private static long getUserIdFromEnvironment()
            throws IdUnavailableException {
        throw new IdUnavailableException();
    }

    public static void main(String[] args) {
        System.out.println("User ID: " + USER_ID);
    }
}

class IdUnavailableException extends Exception {
}
```
:::